### ISSUE TITLE
Have an option to include Shadows

### ISSUE THREAD

**Issue by BurnedChris** [everdrone/react-native-super-ellipse-mask#4]
I been using these as cards and they look great but it would be amazing to also be able to sue shadows

**Comment by everdrone** [comment]
Hey @Burnsy! thanks for the kind words!

Shadows are indeed on my todo list.
I guess the best option is to instantiate `SuperEllipseViewMask` as subclass of `RCTView` instead of `UIView`, and then to override the drawing function alongside with the border masking method.

This should make the library compatible with the Animated API (https://github.com/everdrone/react-native-super-ellipse-mask/issues/3), bring the ability to cast shadows via the `style` prop, like React Native's `<View/>` and enable the border styling capabilities (such as `borderWidth` and `borderColor`).

**Comment by everdrone** [comment]
I find it very tricky for an Obj-C newbie

If anyone experienced has suggestions on how to bring this to life, feel free to open a PR!

**Comment by everdrone** [comment]
New module [SquircleView](https://github.com/everdrone/react-native-squircle-view) now has support for shadows
